[package]
name = "try-trie"
version = "0.1.0"
authors = ["Sara Farquharson <51892187+sfarqu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapsize = "0.4.2"
